### PR TITLE
IRuby::Input

### PR DESCRIPTION
**Pull request by kylekyle**
The `IRuby::Input` class makes it easier to interactively get input from users. This is basically a port of the input widgets in [ipywidgets](ipywidgets button). 

The only change made to core classes was the addition of the stdin socket for `IRuby::Sessions`. This is another socket to receive input on while the main socket is waiting for the backend to return a result. It's the same socket used by python kernels to get input. 

There are lots of examples and documentation in the [README notebook](https://github.com/kylekyle/iruby/blob/input/lib/iruby/input/README.ipynb).

### CODE REVIEW

**Comment by v0dro** [comment]
Looks great and a much needed improvement :)

@minad can you have a look too?

**Comment by minad** [comment]
Great work! Looking very much forward to have this in! I didn't go through it in detail - two comments however:

1. Could you clean up the commit history a bit?
2. I am a bit worried about pulling in too many dependencies? Is erector necessary, or could this be solved more directly? If erector is needed would it be possible to pull it in lazily only if the widgets are used (as an optional gem dependency)?

**Comment by minad** [comment]
@kylekyle Btw, would you be interested in contributing further and to have commit rights?

**Comment by kylekyle** [comment]
@minad: cleaned up the history. It was pretty out of control. 

Yeah, I understand the need to keep dependencies minimal. I could certainly autoload the `IRuby::Input` class and raise an exception then if erector is not installed. Would that work? 

I use and support Jupyter/IRuby everyday at work, so if you would like another maintainer, I'm happy to help!

**Comment by kylekyle** [comment]
@minad: I removed the erector dependency and issue an error if the widgets are used without it. What do you think?

**Comment by minad** [comment]
this is better :)

**Comment by minad** [comment]
@kylekyle Great that you use it all day :) I added you as a collaborator

**Comment by minad** [comment]
@v0dro I also added you as a gem owner. I think it would be best to coordinate the gem releases via github issues.

**Comment by v0dro** [comment]
Thanks! Will do.

I think this is fit for merge now.

**Comment by kylekyle** [comment]
Any chance someone could release a new gem?

**Comment by v0dro** [comment]
@minad can do that.

**Comment by minad** [comment]
@v0dro You are gem owner too. Feel free to release when you think it is ready :)

**Comment by v0dro** [comment]
Oh ok I hadn't noticed. On it.

**Comment by newtonapple** [comment]
This is great.  When are you guys plan on releasing the new gem?  Also, do you have plan to support input range?

**Comment by kylekyle** [comment]
Is there anything I can do too help with this release?

**Comment by v0dro** [comment]
I'll be releasing a new gem by tomorrow. I'm writing the CHANGELOG right now.

**Comment by minad** [comment]
perfect :+1:

**Comment by kylekyle** [comment]
Thanks @v0dro!

**Comment by v0dro** [comment]
its done. have a look!

**Pull request merged**
