### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by kojix2**
Hello!

I think this pull request will make the README document more attractive.
I am not going to change the content of the document.
@mrkn  Please check and fix it.
 
At the next pull request I am planning to replace the captured image in README.

### CODE REVIEW

**Comment by kojix2** [comment]
I thought that potential IRuby users are using Windows. In my opinion, the character string "Windows" gives us the impression that IRuby project takes care of beginners. The message that it is easy for beginners wll attract new users including Mac/Linux users. This is what I thought.

However, it seems that real IRuby users prefer Mac and Ubuntu. Actually, I mainly use Ubuntu and Mac. Not Windows. So "potential IRuby users" may be illusions.

**Comment by mrkn** [comment]
I don't want to act by just speculation. If some data illustrates the many IRuby users use it on Windows, this reordering is appropriate.  If no data, we should keep the order, IMHO.

The rewriting the explanation seems good for me.
So, I want to merge this after restoring the order of operating systems.

By the way, I think we should describe how to use IRuby on Docker for many potential users (it can be done with rubydata/notebooks image).

**Comment by kojix2** [comment]
OK. I will try.

**Comment by kojix2** [comment]
I have never used Docker.
Is there a binder link or something?

**Comment by kojix2** [comment]
All right.
I fixed the pull request.

**Comment by mrkn** [comment]
@kojix2 Thank you very much!

**Pull request merged**
