### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by zheng-yongping**
1.  error message line number
before:
image
image
image
after:
image
image
image

2. error message backtrace
before:
image
after:
image

### CODE REVIEW

**Comment by kojix2** [comment]
Hello @zheng-yongping
Thank you for your pull request. 
I think the new feature looks good. 
Let us check a little more.

ping @mrkn

**Comment by zheng-yongping** [comment]
@kojix2
Sorry, my code depends on ruby2.6’s new infinite range syntax, it doesn't work well with ruby2.5.

https://github.com/zheng-yongping/iruby/blob/ac9763bbde4c7ce84c593cc376da2233c65e42c1/lib/iruby/kernel.rb#L108

when rindex return nil => ArgumentError (bad value for range)

What should I do?

**Comment by kojix2** [comment]
@zheng-yongping

You are right. 
For Ruby 2.5 and earlier, we must check nil.
why don't you add some commit to this branch and make pull request again?

**Comment by mrkn** [comment]
@zheng-yongping Could you please make a new pull request to fix it?

**Comment by zheng-yongping** [comment]
@kojix2 @mrkn
Sorry, I am new to GitHub and don't know if I should make a new pull request.

Here is the fix.
https://github.com/SciRuby/iruby/pull/250

**Pull request merged**
