### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kozo2**
see also https://github.com/SciRuby/iruby/issues/114#issuecomment-277517915

### CODE REVIEW

**Comment by v0dro** [comment]
Why install from the github source? Isn't the latest master released yet?

**Comment by kozo2** [comment]
@v0dro Yes
Yes, it is not released

**Comment by v0dro** [comment]
Sorry for the delay. I will release it today.

**Comment by v0dro** [comment]
@kozo2 iruby 0.3 is released. Can you please install from rubygems and see if it works properly?

**Comment by kozo2** [comment]
@v0dro looks like no problem. thanks.

**Pull request merged**
