### PR TITLE
Support CZTop

### LINKED ISSUE #106: Support cztop
[cztop](https://github.com/paddor/cztop) is a new czmq binding built with ffi.
It is actively maintained now while rbczmq and ffi-rzmq are not actively maintained.
[Kou tried to get admin-bit of rbczmq, but it was failed](https://github.com/methodmissing/rbczmq/issues/61).
I think it will be a new standard zeromq library because the author actively maintains it.
So we need to support cztop.

### PR DESCRIPTION
**Pull request by kou**
Fix #106

### CODE REVIEW

**Comment by kozo2** [comment]
I checked this worked on my Windows env.

**Comment by kozo2** [comment]
I checked this cztop support also worked on Ubuntu xenial env.

**Comment by LunarLanding** [comment]
cztop according to its [README.md](https://github.com/paddor/cztop/blob/master/README.md#requirements) requires CZMQ and ZMQ.
I confirmed that without installing these, iruby complains:

    You should install cztop, rbczmq or ffi_rzmq before running iruby notebook. See README.

I'm tryin to install cztop on Ubuntu, but it's being difficult. On OSX I had no problem, since homebrew simplifies the installation of zmq and czmq. Might be related to https://github.com/paddor/czmq-ffi-gen/issues/6

**Comment by kou** [comment]
If you want to use system CZMQ on Ubuntu 16.04, use the following `Gemfile`:

```text
source "https://rubygems.org/"

gem "pry"
gem "cztop", "< 0.3.0"
gem "iruby", github: "SciRuby/iruby"
```

**Comment by LunarLanding** [comment]
That works on Ubuntu, thanks.

**Pull request merged**
