### PR TITLE
add after_initialize hooks

### PR DESCRIPTION
**Pull request by Yuki-Inoue**
Hello iruby maintainers,

Recently, I've been writing a gem to integrate rails into jupyter (or jupyter to rails). https://github.com/Yuki-Inoue/jupyter_on_rails

Basically, this gem makes it easy to use jupyter on a rails app, by defining a rake task to start a jupyter server configured for that rails app, so that a kernel for loading the rails app (something like `rails c`)will be available.  (I think this would solve #52 problem.)

There, I noticed some gems require the `IRuby::Kernel` to be started prior to those gem's initialization, which makes it impossible for the Rails app to be initialized by the boot_file of the kernel. https://github.com/SciRuby/iruby/blob/e231cf666261543b9d5f7a4078ba867d27f86c91/lib/iruby/command.rb#L66

I worked this around by extending the `IRuby::Kernel#run` method, and doing all the Rails initialization just before the kernel starts the dispatch loop, but I think this implementation is not so clean. (FWIW, this is the code for such hack: https://github.com/Yuki-Inoue/jupyter_on_rails/blob/master/lib/jupyter_on_rails/boot.rb and https://github.com/Yuki-Inoue/jupyter_on_rails/blob/master/lib/jupyter_on_rails/iruby_kernel_extention.rb )

IMHO, there will be also some other cases where someone wants to add some hooks to the kernel startup process, on after the Kernel creation but before the actual `Kernel#run`, I thought it would be beneficial to implement a hook of such in this kernel itself.

So, I've created this PR, which basically allows the boot of kernel to add hook against `after_initialize`.  FWIW, with this feature, my implementation would not need to hack the Kernel class, so it would be much more clean, as seen in this PR: https://github.com/Yuki-Inoue/jupyter_on_rails/pull/2/files

... Any opinion?

### CODE REVIEW

**Comment by mrkn** [comment]
@Yuki-Inoue Could you write the unit test for this new feature?

Although the CI doesn't work well, I want to collect tests for new features.

**Comment by kojix2** [comment]
I think the Jupyter-Rails integration is important for many Rubyists. Though I'm a hobbyist programmer and I don't know Rails. 
@Yuki-Inoue
You look busy these days. I mean, I saw your GitHub calendar. Your coding time seems to be decreasing these months. Can you write a test code?

**Comment by horacio** [comment]
@Yuki-Inoue @kojix2 I can help adding the corresponding tests if needed.

**Comment by mrkn** [comment]
@horacio It's very helpful for us.

**Comment by Yuki-Inoue** [comment]
Hi, sorry for late reply...  As kojix2 mentioned, I had been a bit busy and couldn't spare time...

Writing test for this feature is not trivial ( at least for me ), so I'd also be glad if anyone (or namely @horacio ) could help.

**Comment by ankane** [comment]
Hey @Yuki-Inoue, love this feature. Here's a working test case for it (`test/kernel_test.rb`). Not sure if there's a better way to generate a fake config file for testing.

```ruby
require 'test_helper'
require 'json'

module IRubyTest
  class KernelTest < TestBase
    def test_after_intialize_hooks
      ran_hook = false
      IRuby::Kernel.after_initialize do
        ran_hook = true
      end

      IRuby.logger ||= Logger.new(nil)
      IRuby::Kernel.new(config_file.path)

      assert ran_hook
    ensure
      IRuby::Kernel.after_initialize_hooks.clear
    end

    def config_file
      config_file = Tempfile.new
      config_file.write({key: ""}.to_json)
      config_file.flush
      config_file
    end
  end
end
```

**Comment by Yuki-Inoue** [comment]
@kojix2 @mrkn (to maintainers)

I've added the test from @ankane .
Could you check if this is enough?

**Comment by mrkn** [comment]
@Yuki-Inoue @ankane Thank you for your works.  I'll look at it.

**Comment by mrkn** [comment]
@Yuki-Inoue I wrote event manager in #295.  I'd like to introduce `after_initialize` event by using this event manager.  I'll do it in another pull request, and I'll credit you as co-author in the commit message.  Thank you for your contribution, and I'm very sorry for the late response.

**Pull request closed without merging**
