### PR TITLE
Use jupyter directory

### PR DESCRIPTION
**Pull request by mrkn**
I want to change the location where IRuby kernel is going to be installed to Jupyter's data directory.
And I want to warn users IPython's directory is deprecated.

### TODO

- [x] Change the kernel registration destination
- [x] Warn for use of IPYTHONDIR
- [x] Warn for use of both JUPYTER_DATA_DIR and IPYTHONDIR
- [ ] Handle the existing IRuby kernel in IPython's directory

### CODE REVIEW

**Comment by mrkn** [comment]
I think it is enough to warn there is IRuby kernel in IPython's directory.
Does anyone have different ideas?

**Comment by rgbkrk** [comment]
Warning is fine, migrating them to the jupyter data dir is better.

**Comment by kojix2** [comment]
Great and fine work.
But, I think simply relying on the `jupyter kernelspec` command may be the more resistant way because Jupyter developers may change the installation location in the future. There are few maintainers of IRuby now. I think Simply relying on the `jupyter kernelspec` has the advantage that people with little programming skills can maintain with less code and less effort.

https://github.com/IRkernel/IRkernel/blob/d9ed0e0e49143c1ea228c00ce15b9b66f8ae7bcf/R/installspec.r#L42

**Comment by mrkn** [comment]
@kojix2 This pull-request is ready to be merged.
I don't want to make additional changes here because I want to keep a pull-request simple.

Please make a pull-request to rewrite the installation routine with `jupyter kernelspec` command based on the master branch after merging this pull-request.

**Pull request merged**
