### PR TITLE
Capture STDOUT/STDERR

### LINKED ISSUE #78: No STDOUT in IRuby
In IRuby `$stdout` works, but `STDOUT` doesn't:

```ruby 
STDOUT.puts 'heyo'  # nothing
$stdout.puts 'heyo' # => heyo
```

This breaks a lot of gems, including [hexdump](https://github.com/postmodern/hexdump).

### PR DESCRIPTION
**Pull request by kylekyle**
Points STDOUT and STDERR to $stdout and $stderr. Fixes numerous gems that use the constant instead of the globals.

### CODE REVIEW

**Comment by minad** [comment]
the other gems should be fixed, or maybe overwrite it for compatibility and provide the real stdout and real stderr by the globals $real_stdout, $real_stderr and REAL_STDOUT, REAL_STDERR?

**Comment by minad** [comment]
Or we could provide IRuby::REAL_STDOUT and IRuby::REAL_STDERR?

**Comment by minad** [comment]
lib/iruby/command.rb writes to STDERR for example, this should write to REAL_STDERR then instead

**Comment by kylekyle** [comment]
I'm working on this. There are still some native extensions whose output mysteriously disappears. @minad: Thanks for the `REAL_STDERR` idea, I missed that.

**Comment by kylekyle** [comment]
It looks like C libraries need a file-backed IO for stadard output and standard input. The only way to capture the output of those libraries is to [reopen](http://ruby-doc.org/core-2.3.0/IO.html#method-i-reopen) `STDOUT` and `STDERR` with a file-backed IO that we control. 

I added the `IRuby::RedirectOutput` module which adds a `redirect_output` method to `IRuby::PlainBackend` and `IRuby::PryBackend`. Any output generated within the block to `redirect_output` will be written to the proper `IRuby::Stream` regardless of how it was written to output. Any output written to outside of those blocks will go to the logger like normal. 

A few of my users that maintain C extensions have been testing this patch for the last few days and it seems to work well. 

@minad: let me know what you think.

**Comment by minad** [comment]
I don't like it very much. Seems to be too much work for too little gain. Why are the other gems not using $stdout as they should :(

Am 19. Mai 2016 03:48:53 MESZ, schrieb Kyle <notifications@github.com>:

**Comment by kylekyle** [comment]
The problem this pull request is addressing is the need for certain C libraries to have standard output and error backed by file descriptors. The `IRuby::OStream` class doesn't work in those extensions since they're not actual `IO`s. 

But you have a point. It is a lot of work for little gain. The user with the C extension issue solved it by adding an exception where they once had a message to standard error. I opened an [issue against the hexdump gem](https://github.com/postmodern/hexdump/issues/6) for writing to `STDOUT` directly. 

So I'll close this and we'll fix gems that write directly `STDOUT` and `STDERR` as we discover them.

**Pull request closed without merging**
